let Name = "Harsh Gupta";
let School = "Masai";
let Grade = "A+";
let Section = "BCA";
let Roll_no = 21;
let Computer, Math, Hindi;
Computer = 75;
Math = 80;
Hindi = 90;
Marks = Computer + Math + Hindi;
console.log("Name:",Name);
console.log("School:",School);
console.log("Grade:",Grade);
console.log("Section:",Section);
console.log("Roll No:",Roll_no);
console.log("Computer:",Computer);
console.log("Math:",Math);
console.log("Hindi:",Hindi);
console.log("Total Marks:",Marks);